{
 "title": "Rubbergod Metrics",
 "description": "This is a dashboard for the discord-ext-prometheus Python library.",
 "tags": [ "Discord" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(discord_connected,job)"
    }
   },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Command Count",
   "type": "bargauge",
   "description": "Since last reboot",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "discord_event_on_interaction_total{job=~\"$job\", command!=\"None\"}",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "discord_stat_total_users{job=~\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "discord_stat_total_guilds{job=~\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "discord_stat_total_channels{job=~\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "discord_stat_total_commands{job=~\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - process_start_time_seconds{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Over Time",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "discord_connected{job=~\"$job\", shard=\"None\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "discord_connected{job=~\"$job\",shard=~'[0-9]+'}",
     "legendFormat": "{{job}} : {{shard}}"
    }
   ]
  },
  {
   "title": "Guilds Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "discord_stat_total_guilds{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Discord Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "discord_latency_seconds{job=~\"$job\", shard=~\"[0-9]+\"}",
     "legendFormat": "{{job}} : {{shard}}"
    },
    {
     "expr": "discord_latency_seconds{job=~\"$job\", shard=\"None\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Command Activity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "round(sum(rate(discord_event_on_command_total{job=~\"$job\"}[1m])) by (job, command) * 45)",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "round(sum(rate(discord_event_on_interaction_total{job=~\"$job\", command=~\"None\"}[1m])) by (job, interaction) * 45)",
     "legendFormat": "{{interaction}}"
    },
    {
     "expr": "round(sum(rate(discord_event_on_interaction_total{job=~\"$job\", command!=\"None\"}[1m])) by (job, command) * 45)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Channels Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "discord_stat_total_channels{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Activity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "round(max(rate(logging_total{job=~\"$job\"}[1m])) by (level) * 45)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "discord_stat_total_users{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}