name: Lint

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:
  workflow_call:

jobs:
  pre_commit_ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Set up Python 3.x
      uses: actions/setup-python@v7
      with:
        python-version: 3.x
    - name: Install pre-commit
      run: python -m pip install pre-commit
    - name: Cache pre-commit environments
      uses: actions/cache@v6
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
      if: always()
