name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('requirements*') }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip wheel
        python3 -m pip install --upgrade --upgrade-strategy eager flake8
  
    - name: Run flake8
      run: |
        flake8 .
